ZELLIJ_DIR="$XDG_CONFIG_HOME/zellij"
ZELLIJ_STATUSBAR_SRC="$ZELLIJ_DIR/source/statusbar"
ZELLIJ_STATUSBAR_DEST="$ZELLIJ_DIR/plugins"
ZELLIJ_STATUSBAR_BIN="statusbar.wasm"

mkdir -p "$ZELLIJ_STATUSBAR_DEST"
rm "$ZELLIJ_STATUSBAR_DEST/$ZELLIJ_STATUSBAR_BIN" || true
cd $ZELLIJ_STATUSBAR_SRC
cargo build --release
cp "target/wasm32-wasip1/release/$ZELLIJ_STATUSBAR_BIN" "$ZELLIJ_STATUSBAR_DEST/"
