open /Applications/Alfred\ 4.app;
open /Applications/Autumn.app;
open /Applications/Backup\ and\ sync.app;
open /Applications/Boom\ 2.app;
open /Applications/Captin.app;
open /Applications/Figma.app;
open /Applications/Franz.app;
open /Applications/Google\ Chrome\ Canary.app;
open /Applications/Hammerspoon.app;
open /Applications/Hidden\ Bar.app;
open /Applications/Hyper.app;
open /Applications/iStat\ Menus.app;
open /Applications/jotta.app;
open /Applications/Kap.app;
open /Applications/LyricsX.app;
open /Applications/Muzzle.app;
open /Applications/NordVPN\ IKE.app;
open /Applications/Notion.app;
open /Applications/Numi.app;
open /Applications/Shifty.app;
open /Applications/Spotify.app;
open /Applications/Steam.app;
open /Applications/TotalFinder.app;
open /Applications/TotalSpaces2.app;
open /Applications/Visual\ Studio\ Code\ -\ Insiders.app;
open /System/Applications/Calendar.app;
ssh-add ~/.ssh/personal;
