open -g /Applications/Alfred\ 4.app;
open -g /Applications/Backup\ and\ sync.app;
open -g /Applications/Boom\ 2.app;
open -g /Applications/Captin.app;
open -g /Applications/Discord.app;
open -g /Applications/Figma.app;
open -g /Applications/Google\ Chrome\ Canary.app;
open -g /Applications/Hammerspoon.app;
open -g /Applications/Hidden\ Bar.app;
open -g /Applications/Hyper.app;
open -g /Applications/Kap.app;
open -g /Applications/LyricsX.app;
open -g /Applications/Mullvad\ VPN.app;
open -g /Applications/Muzzle.app;
open -g /Applications/Notion.app;
open -g /Applications/Numi.app;
open -g /Applications/Shifty.app;
open -g /Applications/Spotify.app;
open -g /Applications/TotalFinder.app;
open -g /Applications/Visual\ Studio\ Code\ -\ Insiders.app;
open -g /Applications/WhatsApp.app;
open -g /System/Applications/Calendar.app;
ssh-add ~/.ssh/personal;
