after-login-command = []
after-startup-command = [
  'exec-and-forget borders',
  'workspace browser',
  'layout accordion',
  'workspace design',
  'layout accordion',
  'workspace code',
]
exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  'wallpaper set ~/.config/wallpapers/$AEROSPACE_FOCUSED_WORKSPACE.jpg',
]

start-at-login = true
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 0
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'

[gaps]
inner.horizontal = 16
inner.vertical = 16
outer.left = 16
outer.bottom = 16
outer.top = 16
outer.right = 16

# Define my fancy unicorn key notation
[key-mapping.key-notation-to-key-code]
finder = 'f'
terminal = 't'
code = 'c'
browser = 'b'
design = 'd'
music = 'm'
communication = 'n'
mail = 'o'
productivity = 'p'
remote = 'r'

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]
# Misc
ctrl-cmd-r = ['mode service', 'reload-config', 'mode main', 'balance-sizes']
ctrl-cmd-e = 'balance-sizes'
ctrl-cmd-shift-e = ['balance-sizes', 'flatten-workspace-tree']
ctrl-cmd-b = 'layout tiles'
ctrl-cmd-f = 'layout floating tiling'
ctrl-cmd-m = 'layout accordion tiling'
ctrl-cmd-c = 'split horizontal'
ctrl-cmd-v = 'split vertical'
cmd-backtick = ['focus left', 'focus up']

# Resize windows
ctrl-cmd-minus = 'resize smart -50'
ctrl-cmd-equal = 'resize smart +50'

# Move windows
ctrl-cmd-up = 'move up'
ctrl-cmd-right = 'move right'
ctrl-cmd-down = 'move down'
ctrl-cmd-left = 'move left'

# Move windows between desktops
ctrl-alt-cmd-left = ['move-node-to-monitor next', 'focus-monitor next']
ctrl-alt-cmd-right = ['move-node-to-monitor prev', 'focus-monitor prev']

# Focus windows
ctrl-cmd-shift-up = 'focus up'
ctrl-cmd-shift-right = 'focus right'
ctrl-cmd-shift-down = 'focus down'
ctrl-cmd-shift-left = 'focus left'

# Disable built-in shortcuts
cmd-h = []     # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

# Switch between workspaces
alt-1 = 'workspace finder'
alt-f = 'workspace finder'
alt-2 = 'workspace terminal'
alt-t = 'workspace terminal'
alt-3 = 'workspace code'
alt-c = 'workspace code'
alt-4 = 'workspace browser'
alt-b = 'workspace browser'
alt-5 = 'workspace design'
alt-d = 'workspace design'
alt-6 = 'workspace music'
alt-m = 'workspace music'
alt-7 = 'workspace communication'
alt-n = 'workspace communication'
alt-8 = 'workspace mail'
alt-o = 'workspace mail'
alt-9 = 'workspace productivity'
alt-p = 'workspace productivity'
alt-0 = 'workspace remote'
alt-r = 'workspace remote'

# Move windows to workspaces
ctrl-cmd-1 = ['move-node-to-workspace finder', 'workspace finder']
ctrl-cmd-2 = ['move-node-to-workspace terminal', 'workspace terminal']
ctrl-cmd-3 = ['move-node-to-workspace code', 'workspace code']
ctrl-cmd-4 = ['move-node-to-workspace browser', 'workspace browser']
ctrl-cmd-5 = ['move-node-to-workspace design', 'workspace design']
ctrl-cmd-6 = ['move-node-to-workspace music', 'workspace music']
ctrl-cmd-7 = ['move-node-to-workspace communication', 'workspace communication']
ctrl-cmd-8 = ['move-node-to-workspace mail', 'workspace mail']
ctrl-cmd-9 = ['move-node-to-workspace productivity', 'workspace productivity']
ctrl-cmd-0 = ['move-node-to-workspace remote', 'workspace remote']

[mode.service.binding]
esc = ['reload-config', 'mode main']

# Space - Finder
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = "move-node-to-workspace finder"

# Space - Terminal
[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = "move-node-to-workspace terminal"

# Space - Code
[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = "move-node-to-workspace code"

# Space - Browser
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = "move-node-to-workspace browser"

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = "move-node-to-workspace browser"

# Space - Design
[[on-window-detected]]
if.app-id = 'com.figma.Desktop'
run = "move-node-to-workspace design"

# Space - Music
[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = "move-node-to-workspace music"

# Space - Communication
[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = 'move-node-to-workspace communication'

[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = 'move-node-to-workspace communication'

# Space - Mail
[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
run = 'move-node-to-workspace mail'

# Space - Productivity
[[on-window-detected]]
if.app-id = 'notion.id'
run = 'move-node-to-workspace productivity'

[[on-window-detected]]
if.app-id = 'me.proton.pass.electron'
run = 'move-node-to-workspace productivity'

# Space - Remote
[[on-window-detected]]
if.app-id = 'com.microsoft.rdc.macos'
run = 'move-node-to-workspace remote'
