local alert = require("hs.alert")
local config = require("dotfiles.config")
local slowquit = require("dotfiles.slowquit")
local watcher = require("dotfiles.watcher")
local window = require("dotfiles.window")

config()
slowquit()
watcher()
window()
alert.show("Hammerspoon at your service!", 1.5)
