local alert = require("hs.alert")
local config = require("dotfiles.config")
local hotkeys = require("dotfiles.hotkeys")
local watcher = require("dotfiles.watcher")
local window = require("dotfiles.window")

config()
hotkeys()
watcher()
window()
alert.show("Hammerspoon at your service!", 1.5)
