allowBuilds:
  msgpackr-extract: false
minimumReleaseAgeExclude:
  - '@opencode-ai/ai@0.0.0-beta-17963'
  - '@opencode-ai/client@0.0.0-beta-17963'
  - '@opencode-ai/plugin@0.0.0-beta-17963'
  - '@opencode-ai/protocol@0.0.0-beta-17963'
  - '@opencode-ai/schema@0.0.0-beta-17963'
