"$schema" = 'https://starship.rs/config-schema.json'

format = "$all $fill $jobs$time$line_break$character"
command_timeout = 1000

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[fill]
symbol = " "

[directory]
truncation_length = 8

[time]
disabled = false
time_format = "%R"
format = '[♥](bold red) [$time](bold cyan)'

[git_status]
ahead = "${count}"
diverged = "󰹹${ahead_count}${behind_count}"
behind = "${count}"

[git_branch]
symbol = "󰘬 "

[ruby]
disabled = true

[dotnet]
disabled = true

[nodejs]
disabled = true
