theme = "catppuccin-mocha"

[editor]
color-modes = true
cursorline = true
true-color = true
mouse = true
line-number = "relative"
bufferline = "multiple"
popup-border = "all"
completion-trigger-len = 1
gutters = ["diagnostics", "spacer", "diff", "line-numbers", "spacer", "spacer"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spacer", "version-control", "diagnostics"]
center = ["file-name"]
right = ["selections", "position", "file-encoding", "spinner", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
y = "yank_joined_to_clipboard"
p = ["paste_clipboard_after", ":w"]
P = ["replace_selections_with_clipboard", ":w"]
d = ["delete_selection", ":w"]
"Cmd-s" = ":w!"
"Cmd-r" = ":config-reload"

[keys.select]
y = "yank_joined_to_clipboard"
p = ["replace_selections_with_clipboard", ":w"]
P = ["replace_selections_with_clipboard", ":w"]
d = ["delete_selection", ":w"]
"Cmd-s" = ":w!"
"tab" = "indent"
"S-tab" = "unindent"

[keys.insert]
"Cmd-s" = [":w!", "normal_mode"]
"C-space" = "completion"
"tab" = "indent"
"S-tab" = "unindent"
