long_uptime = true
long_shell = false
current_shell = false
physical_cores = true
theme = "simple"
show = [
  "OperatingSystem",
  "Resolution",
  "Terminal",
  "Shell",
  "Packages",
  "Uptime",
  "Battery",
]
