#!/usr/bin/env lua

-- This is only needed once to install the sketchybar module (or for an update of the module)
os.execute("make -C ./weather/scripts > /dev/null 2>&1 || true")
os.execute("chmod +x ./install.sh && ./install.sh")

-- Add the sketchybar module to the package cpath (the module could be
-- installed into the default search path then this would not be needed)
package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

require("init")
