#!/usr/bin/env lua

local scripts = {
  "install",
  "copy-shared",
  "bars",
}

for _, value in ipairs(scripts) do
  local path = string.format("$HOME/.config/sketchybar/scripts/%s.sh", value)
  local script = string.format("chmod +x %s && %s", path, path)

  os.execute(script)
end

-- Add the sketchybar module to the package cpath (the module could be
-- installed into the default search path then this would not be needed)
package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

require("init")
