shell = "zsh"


# defer
# ----------------------

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"


# core modules
# ----------------------

[plugins.colors]
local = "~/.config/zsh/modules"
use = ["{colors,compinit,macOS}/*.plugin.zsh"]


# Syntax highlighting
# ----------------------

[plugins.syntax-highlight]
github = "marcosmoura/fast-syntax-highlighting"
apply = ["defer"]


# Completions
# ----------------------

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.dotfiles-completions]
local = "~/.config/zsh/modules/completions"
use = ["*.plugin.zsh"]

[plugins.yarn-completion]
github = "chrisands/zsh-yarn-completions"
apply = ["defer"]

[plugins.nx-completion]
github = "jscutlery/nx-completion"
apply = ["defer"]

[plugins.pnpm-completion]
github = "g-plane/pnpm-shell-completion"
apply = ["defer"]


# omz plugins
# ----------------------

[plugins.ohmyzsh-lib]
github = "ohmyzsh/ohmyzsh"
dir = "lib"
use = ["{compfix,completion,git,grep,history,key-bindings}.zsh"]

[plugins.ohmyzsh-plugins]
github = "ohmyzsh/ohmyzsh"
dir = "plugins"
use = ["{aliases,cp,dircycle,github,zoxide}/*.plugin.zsh"]


# Other plugins
# ----------------------

[plugins.256color]
github = "chrissicool/zsh-256color"

[plugins.zoxide]
github = "ajeetdsouza/zoxide"

[plugins.zsh-you-should-use]
github = "MichaelAquilina/zsh-you-should-use"
apply = ["defer"]


# Dotfiles
# ----------------------

[plugins.dotfiles]
local = "~/.config/zsh/modules"
use = ["*.plugin.zsh", "!{colors,completions,compinit,macOS}/*.plugin.zsh"]
