shell = "zsh"

# ==============================================================================
# DEFER SETUP
# ==============================================================================
# Template for deferred loading to improve shell startup time

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

# ==============================================================================
# CORE SYSTEM MODULES
# ==============================================================================
# Essential functionality that needs to load early

[plugins.core-system]
local = "~/.config/zsh/modules"
use = ["{colors,compinit,macOS}/*.plugin.sh"]

# ==============================================================================
# OH-MY-ZSH FOUNDATION
# ==============================================================================
# Core zsh functionality from oh-my-zsh

[plugins.ohmyzsh-lib]
github = "ohmyzsh/ohmyzsh"
dir = "lib"
use = ["{compfix,completion,git,grep,history,key-bindings}.zsh"]

[plugins.ohmyzsh-plugins]
github = "ohmyzsh/ohmyzsh"
dir = "plugins"
use = ["{aliases,cp,dircycle,github,zoxide}/*.plugin.zsh"]

# ==============================================================================
# SHELL ENHANCEMENTS
# ==============================================================================
# Visual and interactive improvements

[plugins.256color]
github = "chrissicool/zsh-256color"

[plugins.syntax-highlight]
github = "marcosmoura/fast-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zsh-you-should-use]
github = "MichaelAquilina/zsh-you-should-use"
apply = ["defer"]

# ==============================================================================
# COMPLETION SYSTEM
# ==============================================================================
# Tab completion for various tools and commands

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

# Custom completions from dotfiles
[plugins.dotfiles-completions]
local = "~/.config/zsh/modules/completions"
use = ["*.plugin.sh"]

# Node.js ecosystem completions
[plugins.yarn-completion]
github = "chrisands/zsh-yarn-completions"
apply = ["defer"]

[plugins.nx-completion]
github = "jscutlery/nx-completion"
apply = ["defer"]

[plugins.pnpm-completion]
github = "g-plane/pnpm-shell-completion"
apply = ["defer"]

# ==============================================================================
# NAVIGATION & UTILITIES
# ==============================================================================
# Tools for better directory navigation and file management

[plugins.zoxide]
github = "ajeetdsouza/zoxide"

# ==============================================================================
# CUSTOM DOTFILES MODULES
# ==============================================================================
# Personal shell configuration modules

[plugins.dotfiles-modules]
local = "~/.config/zsh/modules"
use = ["*.plugin.sh", "!{colors,completions,compinit,macOS}/*.plugin.sh"]
