approval_policy = "on-request"
sandbox_mode = "workspace-write"
personality = "pragmatic"
approvals_reviewer = "guardian_subagent"
model = "gpt-5.4"
model_reasoning_effort = "medium"
plan_mode_reasoning_effort = "medium"

[sandbox_workspace_write]
network_access = false

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"
env_http_headers = { "CONTEXT7_API_KEY" = "CONTEXT7_API_KEY" }

[mcp_servers.grep]
url = "https://mcp.grep.app"

[mcp_servers.github]
url = "https://api.githubcopilot.com/mcp/"
bearer_token_env_var = "GH_PAT"

[mcp_servers.figma]
url = "https://mcp.figma.com/mcp"

[projects."/Users/marcosmoura/Projects/sonora"]
trust_level = "trusted"

[features]
guardian_approval = true
prevent_idle_sleep = true
multi_agent = true

[tui]
status_line = ["model-with-reasoning", "context-remaining", "current-dir", "five-hour-limit", "weekly-limit", "session-id", "fast-mode"]

[notice.model_migrations]
"gpt-5.1-codex-mini" = "gpt-5.4"
"gpt-5.3-codex" = "gpt-5.4"

[plugins."figma@openai-curated"]
enabled = true
