approval_policy = "on-request"
sandbox_mode = "workspace-write"
personality = "pragmatic"
approvals_reviewer = "guardian_subagent"
model = "gpt-5.4-mini"
model_reasoning_effort = "medium"
plan_mode_reasoning_effort = "medium"

[sandbox_workspace_write]
network_access = false

[mcp_servers.grep]
url = "https://mcp.grep.app"

[mcp_servers.github]
url = "https://api.githubcopilot.com/mcp/"
bearer_token_env_var = "GH_PAT"

[features]
guardian_approval = true
prevent_idle_sleep = true
multi_agent = true
fast_mode = true
terminal_resize_reflow = true
memories = true
goals = true

[tui]
status_line = [
  "model-with-reasoning",
  "fast-mode",
  "context-remaining",
  "context-window-size",
  "git-branch",
  "session-id",
  "current-dir",
]

[notice.model_migrations]
"gpt-5.1-codex-mini" = "gpt-5.4"

[plugins."superpowers@openai-curated"]
enabled = true

[projects."/Users/marcosmoura/Projects/dotfiles"]
trust_level = "trusted"

[projects."/Users/marcosmoura/stripe/mint"]
trust_level = "trusted"

[marketplaces.stripe-internal-marketplace]
last_updated = "2026-06-08T09:52:05Z"
last_revision = "f5ddf4ed183788bca11bdf828cb30833c22ea682"
source_type = "git"
source = "http://codex-marketplace--northwest.corp.stripe.com.certproxy.localhost:7891/codex-marketplace.git"
